### ISSUE TITLE
Trouble compiling c# binding

### ISSUE THREAD

**Issue by bzuidgeest** [ilixi/ilixi#1]
While looking for a way to use directfb with mono on arm I came across ilixi. Not only did i look nice, it had, much to my surprise, an c# binding. After checking it out from git I tried to build it but got an error building the .net library. I get errors in the generated TextBase class as you can read below. 

Looking in the swig/csharp/gen for the TextBase class I find the line 
Private HandleRed swigCPtr;
In other files like TabPanel.cs I find the same declaration only than with the full namespace:
private global::System.Runtime.InterosServices.HandleRef swigCPtr;

Both files contain no using statements what so ever for namespace declaration. Making that the declaration as in TabPanel.cs is needed. But I do not know anything about how swig works so I cannot say why it failed to add the full namespace to the TextBase class. 

Can somebody help me out?

gen/Widget.cs(399,23): (Location of the symbol related to previous warning)
gen/TabPanelButton.cs(46,23): warning CS0114: `ilixi.TabPanelButton.preferredSize()' hides inherited member`ilixi.Widget.preferredSize()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword
gen/Widget.cs(153,23): (Location of the symbol related to previous warning)
gen/TextBase.cs(15,50): error CS0246: The type or namespace name `Object' could not be found. Are you missing`System' using directive?
gen/TextBase.cs(17,11): error CS0246: The type or namespace name `HandleRef' could not be found. Are you missing`System.Runtime.InteropServices' using directive?
gen/TextBase.cs(20,21): error CS0246: The type or namespace name `IntPtr' could not be found. Are you missing`System' using directive?
gen/TextBase.cs(26,19): error CS0246: The type or namespace name `HandleRef' could not be found. Are you missing`System.Runtime.InteropServices' using directive?
gen/ToolButton.cs(53,15): warning CS0114: `ilixi.ToolButton.preferredSize()' hides inherited member`ilixi.Widget.preferredSize()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword
gen/Widget.cs(153,23): (Location of the symbol related to previous warning)
gen/VBoxLayout.cs(62,23): warning CS0114: `ilixi.VBoxLayout.preferredSize()' hides inherited member`ilixi.LayoutBase.preferredSize()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword
gen/LayoutBase.cs(48,23): (Location of the symbol related to previous warning)
Compilation failed: 24 error(s), 29 warnings
Makefile:1068: recipe for target 'ilixi.dll' failed
make[3]: **\* [ilixi.dll] Error 1
make[3]: Leaving directory '/root/ilixi/swig/csharp'
Makefile:435: recipe for target 'all-recursive' failed
make[2]: **\* [all-recursive] Error 1
make[2]: Leaving directory '/root/ilixi/swig'
Makefile:589: recipe for target 'all-recursive' failed
make[1]: **\* [all-recursive] Error 1
make[1]: Leaving directory '/root/ilixi'
Makefile:497: recipe for target 'all' failed
make: **\* [all] Error 2

**Comment by bzuidgeest** [comment]
No response yet :(.

Did some digging of my own. I found that all problem files had the line %include "csgcfix.i". I removed this line and all files had proper namespaces and the dll compiled. From the name I gather it fixes some problem involving garbage collection....

Unfortunately I than got a compile failure on combobox but that is cpp and even less familiar to me. Hope the source tree in github is not completely busted. I was actually looking forward to having a nice framework for c# on a directfb console.

**Comment by bzuidgeest** [comment]
From Combobox.i

%extend ilixi::ComboBox {
  void connectSelectionChanged(DelegateNotify cb)
  {
    $self->sigSelectionChanged.connect(sigc::ptr_fun(cb));
  }
}

I get an compile error that sigSelectionChanged does not exist. Looking a cpp source history this was removed a a point and replaced with sigItemSelected. Just renaming the stuff in the .i file did not work however. Not supprising as the cpp function signature is different.

HELP

**Comment by mtsekm** [comment]
It has been a while since I've used C# bindings. Thanks for reporting the issue.

Did you try compiling after removing the connectSelectionChanged method in the interface file?

**Comment by bzuidgeest** [comment]
I did not yet try after removing the connectSelectionChanged method. It was after midnight in my timezone when I got to that point. Planning to try tonight.

**Comment by bzuidgeest** [comment]
I removed the method and then compilation went fine. I guess the method has it's uses though.

I tried running the demos but they all error out complaining they cannot find ilixi_config.xml. The path that is searched starts with NONE for some reason. Seems ILIXI_DATADIR was not set by compile script or somthing going to retry

**Comment by mtsekm** [comment]
Thanks for the info. I'm going to test it over the weekend. Hope to fix this soon.

**Comment by mtsekm** [comment]
I have pushed a few commits and added a page on website.
http://www.ilixi.org/documentation/csharp-bindings/

It should build from master now. I can run test applications on X11.

**Comment by bzuidgeest** [comment]
That is very good to hear, I hope to be able to test tonight. Will let you know the results

**Comment by bzuidgeest** [comment]
I compiled the latest version last night, and I observed no problems. A quick test with the demos gave me only a black screen with a cursor on fb console. However that is most likely some problem with directFB on my testsystem (raspberry pi with arch). 

I started this issue because of compiling problems and those are solved so I consider this closed. 

Thanks for all the support.
